### ISSUE TITLE
Compatibility With Modern Warfare Mod

### ISSUE THREAD

**Issue by kenijey** [kenijey/FirstPersonRender#3]
**if possible;**
        if the item that player hold in hand is from modern warfare mod;
                             render default hands but render realistic body(except hands)
**if not possible;**
                              disable mod (render default/vanilla style hands) if player holds an item from warfare mod

**Comment by Wyn-Price** [comment]
I'll see if I can do it. At the moment I'm doing the secret rooms mod but that should be done within like a week so I can look into this then

**Comment by kenijey** [comment]
ok thats good. btw did u get perm for that mod?

**Comment by Wyn-Price** [comment]
The owner kinda gave anyone permission in the comments, but I have asked for it anyway

**Comment by kenijey** [comment]
nice
