### ISSUE TITLE
Transfer of issue from DonBruce64/RealFirstPersonRender

### ISSUE THREAD

**Issue by DonBruce64** [kenijey/FirstPersonRender#6]
Issue was submitted on my codbase.  It belongs on your codbase instead.  Submitting an issue ticket here and referencing the issue chain on my repo.  Unsubscribing myself to avoid extra e-mails.
https://github.com/DonBruce64/RealFirstPersonRender/issues/1

**Comment by Wyn-Price** [comment]
I'll look into it soon. I'm very busy with school and mocks at the moment but if I find extra time I'll look into this. If not I'll be done with the in around 2 weeks so Ill look into it then

**Comment by kenijey** [comment]
it's already fixed long while ago. thanks for doing this Don.
